import Head from 'next/head'
import Page1 from './Components/Page1'
import Page2 from './Components/Page2'
import Page3 from './Components/Page3'
import jsPDF from 'jspdf'

export default function Home() {
  function Download() {
    const date = Date.now()
    let doc = new jsPDF('a4')
    var elementHTML = document.querySelector('#main')
    doc.html(elementHTML, {
      callback: function (doc) {
        doc.save(`Contract-${date}.pdf`)
      },
      x: 15,
      y: 25,
      width: 170,
      windowWidth: 650,
    })
  }
  return (
    <>
      <Head>
        <title>BMF Attorneys Contract</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main id="main">
        <Page1 />
        <Page2 />
        <Page3 />
      </main>
      <button className="btn btn-success m-3 text-center" onClick={Download}>
        Download as PDF
      </button>
    </>
  )
}
